version: '3.8'

services:
  python-app:
    build: .
    env_file: .env.prod
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      
    depends_on:
      - redis
      - postgres
    networks:
      - my-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  redis_data: /data/redis/
  postgres_data: /data/redis/

networks:
  my-network:
    driver: bridge
